#!/bin/bash
set -o errexit

FOLDER=${1:-magento}
DOMAIN=${FOLDER}.box
VERSION=${2:-2.4.3-p1}
EDITION=${3:-community}

mkdir ${FOLDER} && cd ${FOLDER}

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" "${EDITION}" \
  && bin/setup "${DOMAIN}" \
  && bin/magento module:disable Magento_TwoFactorAuth \
  && bin/magento cache:flush
